import { 
  faBrain, 
  faStar, 
  faBolt, 
  faArrowRight, 
  faRobot, 
  faCode, 
  faDatabase, 
  faLightbulb, 
  faTerminal, 
  faCheckCircle, 
  faClock, 
  faHands, 
  faSync, 
  faChartBar, 
  faLock, 
  faRocket, 
  faShieldAlt, 
  faCity, 
  faTachometerAlt, 
  faShoppingCart, 
  faCheck, 
  faX, 
  faChevronDown, 
  faEnvelope, 
  faPhone, 
  faCalendar, 
  faPaperPlane, 
  faGlobe, 
  faBars, 
  faChevronLeft, 
  faChevronRight, 
  faThumbsUp, 
  faThumbsDown, 
  faCopy, 
  faDownload
} from '@fortawesome/free-solid-svg-icons';
import { faLinkedin as faLinkedinBrand, faInstagram as faInstagramBrand, faGithub as faGithubBrand } from '@fortawesome/free-brands-svg-icons';

// Solid icons
export const solidIcons = {
  faBrain,
  faStar,
  faBolt,
  faArrowRight,
  faRobot,
  faCode,
  faDatabase,
  faLightbulb,
  faTerminal,
  faCheckCircle,
  faClock,
  faHands,
  faSync,
  faChartBar,
  faLock,
  faRocket,
  faShieldAlt,
  faCity,
  faTachometerAlt,
  faShoppingCart,
  faCheck,
  faX,
  faChevronDown,
  faEnvelope,
  faPhone,
  faCalendar,
  faPaperPlane,
  faGlobe,
  faBars,
  faChevronLeft,
  faChevronRight,
  faThumbsUp,
  faThumbsDown,
  faCopy,
  faDownload
};

// Brand icons
export const brandIcons = {
  faLinkedin: faLinkedinBrand,
  faInstagram: faInstagramBrand,
  faGithub: faGithubBrand
};
